version: '3.2'
services:
  web:
    build: ./
    restart: always
    command: python3 /src/mysite/manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - 8080:8000
    tty: true
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./web-src"
        target: "/src"
      - /etc/localtime:/etc/localtime:ro

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  mongo:
    image: mongo
    restart: always