# Generated by Django 3.2 on 2022-06-04 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checkuuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='checkuuid')),
                ('bookisbn', models.CharField(max_length=16, verbose_name='bookisbn')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('checkflag', models.BooleanField(default=False, verbose_name='checkflag')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiryuuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='inquiryuuid')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('body', models.TextField(max_length=280, null=True, verbose_name='body')),
                ('tags', models.CharField(max_length=1024, null=True, verbose_name='tags')),
                ('status', models.TextField(null=True, verbose_name='status')),
                ('useruuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='useruuid')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyuuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='replyuuid')),
                ('bookisbn', models.CharField(max_length=16, verbose_name='bookisbn')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('body', models.TextField(max_length=280, null=True, verbose_name='body')),
                ('goods', models.IntegerField(default=0, verbose_name='goods')),
                ('status', models.TextField(null=True, verbose_name='status')),
                ('inquiryuuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bks.inquiry', verbose_name='inquiryuuid')),
                ('useruuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='useruuid')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyuuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bks.reply', verbose_name='replyuuid')),
                ('useruuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='useruuid')),
            ],
        ),
        migrations.CreateModel(
            name='Impress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=280, null=True, verbose_name='body')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('status', models.TextField(null=True, verbose_name='status')),
                ('checkuuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bks.checklist', verbose_name='checkuuid')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='inquiryuuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bks.inquiry', verbose_name='inquiryuuid'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='useruuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='useruuid'),
        ),
    ]
